"""
blocks.py
---------
Builds Slack Block Kit payloads for the RCA incident card.

Responsibility: Pure UI construction — no business logic, no I/O.
"""

from typing import List, Optional


def build_incident_card(
    incident_id: str,
    severity: str,
    namespace: str,
    failed_pod: str,
    failed_service: str,
    root_cause: str,
    diagnosis_summary: str,
    evidence: str,
    impacted_services: List[str],
    blast_radius: int,
    kubectl_command: str,
    timestamp: str,
    confidence: Optional[str] = None,
) -> List[dict]:
    """Returns a Block Kit block list representing a rich RCA incident card.

    The card includes:
      - Header with severity badge
      - Incident metadata (ID, namespace, pod, service)
      - Root cause & diagnosis summary
      - Evidence snippet
      - Impacted services / blast radius
      - Recommended kubectl remediation command

    """
   
    severity_emoji = {
        "critical": "🔴",
        "high": "🟠",
        "medium": "🟡",
        "low": "🟢",
    }.get(severity.lower(), "⚪")

    impacted_list = ", ".join(impacted_services) if impacted_services else "None"
    confidence_text = f"*Confidence:* `{confidence}`\n" if confidence else ""

    blocks = [
        # ── Header ──────────────────────────────────────────────────────────
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"{severity_emoji} RCA Alert — {failed_service} Incident",
                "emoji": True,
            },
        },
        {"type": "divider"},

        # ── Incident Metadata ────────────────────────────────────────────────
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Incident ID:*\n`{incident_id}`"},
                {"type": "mrkdwn", "text": f"*Severity:*\n{severity_emoji} `{severity.upper()}`"},
                {"type": "mrkdwn", "text": f"*Namespace:*\n`{namespace}`"},
                {"type": "mrkdwn", "text": f"*Affected Pod:*\n`{failed_pod}`"},
                {"type": "mrkdwn", "text": f"*Service:*\n`{failed_service}`"},
                {"type": "mrkdwn", "text": f"*Blast Radius:*\n`{blast_radius} service(s)`"},
            ],
        },
        {"type": "divider"},

        # ── Root Cause ───────────────────────────────────────────────────────
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"*🔍 Root Cause*\n"
                    f"> {root_cause}\n\n"
                    f"*📋 Diagnosis Summary*\n"
                    f"> {diagnosis_summary}\n\n"
                    f"{confidence_text}"
                ),
            },
        },
        {"type": "divider"},

        # ── Evidence ─────────────────────────────────────────────────────────
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*📊 Evidence / Observations*\n```{evidence}```",
            },
        },
        {"type": "divider"},

        # ── Impacted Services ────────────────────────────────────────────────
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*🌐 Impacted Services*\n{impacted_list}",
            },
        },
        {"type": "divider"},

        # ── Recommended Remediation ──────────────────────────────────────────
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*💻 Recommended Remediation*\n```{kubectl_command}```",
            },
        },
        {"type": "divider"},


        # ── Footer ───────────────────────────────────────────────────────────
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": f"🤖 Generated by RCA AIops Pipeline | {timestamp}",
                }
            ],
        },
    ]

    return blocks
